// Lista importada por el usuario — Pokémon Champions (IDs y nombres)
// Incluye formas regionales y megaevoluciones tal como proporcionado por el usuario.
// Cada entrada: { id: number, name: string }
const QUESTIONS = [
  { "id": 3, "name": "Venusaur" },
  { "id": 6, "name": "Charizard" },
  { "id": 9, "name": "Blastoise" },
  { "id": 15, "name": "Beedrill" },
  { "id": 18, "name": "Pidgeot" },
  { "id": 24, "name": "Arbok" },
  { "id": 25, "name": "Pikachu" },
  { "id": 26, "name": "Raichu" },
  { "id": 26, "name": "Raichu de Alola", "slug": "raichu-alola" },
  { "id": 36, "name": "Clefable" },
  { "id": 38, "name": "Ninetales" },
  { "id": 38, "name": "Ninetales de Alola", "slug": "ninetales-alola" },
  { "id": 59, "name": "Arcanine" },
  { "id": 59, "name": "Arcanine de Hisui", "slug": "arcanine-hisui" },
  { "id": 65, "name": "Alakazam" },
  { "id": 68, "name": "Machamp" },
  { "id": 71, "name": "Victreebel" },
  { "id": 80, "name": "Slowbro" },
  { "id": 94, "name": "Gengar" },
  { "id": 115, "name": "Kangaskhan" },
  { "id": 121, "name": "Starmie" },
  { "id": 127, "name": "Pinsir" },
  { "id": 128, "name": "Tauros" },
  { "id": 130, "name": "Gyarados" },
  { "id": 132, "name": "Ditto" },
  { "id": 134, "name": "Vaporeon" },
  { "id": 135, "name": "Jolteon" },
  { "id": 136, "name": "Flareon" },
  { "id": 142, "name": "Aerodactyl" },
  { "id": 143, "name": "Snorlax" },
  { "id": 149, "name": "Dragonite" },
  { "id": 154, "name": "Meganium" },
  { "id": 157, "name": "Typhlosion" },
  { "id": 160, "name": "Feraligatr" },
  { "id": 181, "name": "Ampharos" },
  { "id": 184, "name": "Azumarill" },
  { "id": 186, "name": "Politoed" },
  { "id": 196, "name": "Espeon" },
  { "id": 197, "name": "Umbreon" },
  { "id": 199, "name": "Slowking" },
  { "id": 212, "name": "Scizor" },
  { "id": 214, "name": "Heracross" },
  { "id": 229, "name": "Houndoom" },
  { "id": 248, "name": "Tyranitar" },
  { "id": 257, "name": "Blaziken" },
  { "id": 260, "name": "Swampert" },
  { "id": 282, "name": "Gardevoir" },
  { "id": 303, "name": "Mawile" },
  { "id": 306, "name": "Aggron" },
  { "id": 308, "name": "Medicham" },
  { "id": 310, "name": "Manectric" },
  { "id": 330, "name": "Flygon" },
  { "id": 334, "name": "Altaria" },
  { "id": 354, "name": "Banette" },
  { "id": 359, "name": "Absol" },
  { "id": 362, "name": "Glalie" },
  { "id": 392, "name": "Infernape" },
  { "id": 405, "name": "Luxray" },
  { "id": 407, "name": "Roserade" },
  { "id": 423, "name": "Gastrodon" },
  { "id": 445, "name": "Garchomp" },
  { "id": 448, "name": "Lucario" },
  { "id": 460, "name": "Abomasnow" },
  { "id": 461, "name": "Weavile" },
  { "id": 475, "name": "Gallade" },
  { "id": 479, "name": "Rotom", "slug": "rotom" },
  { "id": 479, "name": "Rotom Calor", "slug": "rotom-heat" },
  { "id": 479, "name": "Rotom Lavado", "slug": "rotom-wash" },
  { "id": 479, "name": "Rotom Frío", "slug": "rotom-frost" },
  { "id": 479, "name": "Rotom Ventilador", "slug": "rotom-fan" },
  { "id": 479, "name": "Rotom Corte", "slug": "rotom-mow" },
  { "id": 530, "name": "Excadrill" },
  { "id": 547, "name": "Whimsicott" },
  { "id": 553, "name": "Krookodile" },
  { "id": 569, "name": "Garbodor" },
  { "id": 571, "name": "Zoroark" },
  { "id": 571, "name": "Zoroark de Hisui","slug": "zoroark-hisui"},
  { "id": 579, "name": "Reuniclus" },
  { "id": 609, "name": "Chandelure" },
  { "id": 635, "name": "Hydreigon" },
  { "id": 637, "name": "Volcarona" },
  { "id": 658, "name": "Greninja" },
  { "id": 663, "name": "Talonflame" },
  { "id": 678, "name": "Meowstic" },
  { "id": 683, "name": "Aromatisse" },
  { "id": 700, "name": "Sylveon" },
  { "id": 701, "name": "Hawlucha" },
  { "id": 706, "name": "Goodra" },
  { "id": 706, "name": "Goodra de Hisui", "slug": "goodra-hisui" },
  { "id": 715, "name": "Noivern" },
  { "id": 717, "name": "Yveltal" },
  { "id": 724, "name": "Decidueye" },
  { "id": 724, "name": "Decidueye de Hisui", "slug": "decidueye-hisui" },
  { "id": 727, "name": "Incineroar" },
  { "id": 730, "name": "Primarina" },
  { "id": 745, "name": "Lycanroc" },
  { "id": 748, "name": "Toxapex" },
  { "id": 778, "name": "Mimikyu" },
  { "id": 784, "name": "Kommo-o" },
  { "id": 818, "name": "Inteleon" },
  { "id": 823, "name": "Corviknight" },
  { "id": 826, "name": "Orbeetle" },
  { "id": 858, "name": "Hatterene" },
  { "id": 861, "name": "Grimmsnarl" },
  { "id": 887, "name": "Dragapult" },
  { "id": 892, "name": "Urshifu" },
  { "id": 901, "name": "Ursaluna" },
  { "id": 903, "name": "Sneasler" },
  { "id": 908, "name": "Meowscarada" },
  { "id": 911, "name": "Skeledirge" },
  { "id": 914, "name": "Quaquaval" },
  { "id": 937, "name": "Ceruledge" },
  { "id": 938, "name": "Armarouge" },
  { "id": 959, "name": "Tinkaton" },
  { "id": 964, "name": "Palafin" },
  { "id": 983, "name": "Kingambit" },

  // Megaevoluciones
  { "id": 3, "name": "Mega-Venusaur", "slug": "venusaur-mega" },
  { "id": 6, "name": "Mega-Charizard X", "slug": "charizard-mega-x" },
  { "id": 6, "name": "Mega-Charizard Y", "slug": "charizard-mega-y" },
  { "id": 9, "name": "Mega-Blastoise", "slug": "blastoise-mega" },
  { "id": 15, "name": "Mega-Beedrill", "slug": "beedrill-mega" },
  { "id": 18, "name": "Mega-Pidgeot", "slug": "pidgeot-mega" },
  { "id": 36, "name": "Mega-Clefable", "slug": "clefable-mega" },
  { "id": 65, "name": "Mega-Alakazam", "slug": "alakazam-mega" },
  { "id": 71, "name": "Mega-Victreebel", "slug": "victreebel-mega" },
  { "id": 80, "name": "Mega-Slowbro", "slug": "slowbro-mega" },
  { "id": 94, "name": "Mega-Gengar", "slug": "gengar-mega" },
  { "id": 115, "name": "Mega-Kangaskhan", "slug": "kangaskhan-mega" },
  { "id": 121, "name": "Mega-Starmie", "slug": "starmie-mega" },
  { "id": 127, "name": "Mega-Pinsir", "slug": "pinsir-mega" },
  { "id": 130, "name": "Mega-Gyarados", "slug": "gyarados-mega" },
  { "id": 142, "name": "Mega-Aerodactyl", "slug": "aerodactyl-mega" },
  { "id": 149, "name": "Mega-Dragonite", "slug": "dragonite-mega" },
  { "id": 154, "name": "Mega-Meganium", "slug": "meganium-mega" },
  { "id": 160, "name": "Mega-Feraligatr", "slug": "feraligatr-mega" }
];

// Archivo importado por el usuario. La app puede usar `QUESTIONS` para generar quizzes

// Puedes usar esta variable en la app para forzar el banco Champions.
