// Lista importada por el usuario — Pokémon Champions (IDs y nombres)
// Incluye formas regionales y megaevoluciones tal como proporcionado por el usuario.
// Cada entrada: { id: number, name: string }
const QUESTIONS = [
  { "id": 3, "name": "Venusaur" },
  { "id": 6, "name": "Charizard" },
  { "id": 9, "name": "Blastoise" },
  { "id": 15, "name": "Beedrill" },
  { "id": 18, "name": "Pidgeot" },
  { "id": 24, "name": "Arbok" },
  { "id": 25, "name": "Pikachu" },
  { "id": 26, "name": "Raichu" },
  { "id": 26, "name": "Raichu de Alola", "slug": "raichu-alola" },
  { "id": 36, "name": "Clefable" },
  { "id": 38, "name": "Ninetales" },
  { "id": 38, "name": "Ninetales de Alola", "slug": "ninetales-alola" },
  { "id": 59, "name": "Arcanine" },
  { "id": 59, "name": "Arcanine de Hisui", "slug": "arcanine-hisui" },
  { "id": 65, "name": "Alakazam" },
  { "id": 68, "name": "Machamp" },
  { "id": 71, "name": "Victreebel" },
  { "id": 80, "name": "Slowbro" },
  { "id": 80, "name": "Slowbro Galar", "slug": "slowbro-galar" },
  { "id": 94, "name": "Gengar" },
  { "id": 115, "name": "Kangaskhan" },
  { "id": 121, "name": "Starmie" },
  { "id": 127, "name": "Pinsir" },
  { "id": 128, "name": "Tauros" },
  { "id": 128, "name": "Tauros Paldea", "slug": "tauros-paldea-combat-breed" },
  { "id": 128, "name": "Tauros Paldea Fuego", "slug": "tauros-paldea-blaze-breed" },
  { "id": 128, "name": "Tauros Paldea Agua", "slug": "tauros-paldea-aqua-breed" },
  { "id": 130, "name": "Gyarados" },
  { "id": 132, "name": "Ditto" },
  { "id": 134, "name": "Vaporeon" },
  { "id": 135, "name": "Jolteon" },
  { "id": 136, "name": "Flareon" },
  { "id": 142, "name": "Aerodactyl" },
  { "id": 143, "name": "Snorlax" },
  { "id": 149, "name": "Dragonite" },
  { "id": 154, "name": "Meganium" },
  { "id": 157, "name": "Typhlosion" },
  { "id": 157, "name": "Typhlosion Hisui", "slug": "typhlosion-hisui" },
  { "id": 160, "name": "Feraligatr" },
  { "id": 181, "name": "Ampharos" },
  { "id": 184, "name": "Azumarill" },
  { "id": 186, "name": "Politoed" },
  { "id": 196, "name": "Espeon" },
  { "id": 197, "name": "Umbreon" },
  { "id": 199, "name": "Slowking" },
  { "id": 199, "name": "Slowking Galar", "slug": "slowking-galar" },
  { "id": 205, "name": "Forretress" },
  { "id": 208, "name": "Steelix" },
  { "id": 212, "name": "Scizor" },
  { "id": 214, "name": "Heracross" },
  { "id": 227, "name": "Skarmory" },
  { "id": 229, "name": "Houndoom" },
  { "id": 248, "name": "Tyranitar" },
  { "id": 279, "name": "Pelipper" },
  { "id": 282, "name": "Gardevoir" },
  { "id": 302, "name": "Sableye" },
  { "id": 306, "name": "Aggron" },
  { "id": 308, "name": "Medicham" },
  { "id": 310, "name": "Manectric" },
  { "id": 319, "name": "Sharpedo" },
  { "id": 323, "name": "Camerupt"},
  { "id": 324, "name": "Torkoal" },
  { "id": 334, "name": "Altaria" },
  { "id": 351, "name": "Castform" },
  { "id": 354, "name": "Banette" },
  { "id": 354, "name": "Chimecho" },
  { "id": 359, "name": "Absol" },
  { "id": 362, "name": "Glalie" },
  { "id": 389, "name": "Torterra", "slug": "torterra" },
  { "id": 392, "name": "Infernape" },
  { "id": 395, "name": "Empoleon" },
  { "id": 405, "name": "Luxray" },
  { "id": 407, "name": "Roserade" },
  { "id": 409, "name": "Rampardos" },
  { "id": 411, "name": "Bastiodon" },
  { "id": 428, "name": "Lopunny" },
  { "id": 442, "name": "Spiritomb" },
  { "id": 445, "name": "Garchomp" },
  { "id": 448, "name": "Lucario" },
  { "id": 450, "name": "Hippowdon" },
  { "id": 454, "name": "Toxicroak" },
  { "id": 460, "name": "Abomasnow" },
  { "id": 461, "name": "Weavile" },
  { "id": 464, "name": "Rhyperior" },
  { "id": 470, "name": "Leafeon" },
  { "id": 471, "name": "Glaceon" },
  { "id": 472, "name": "Gliscor" },
  { "id": 473, "name": "Mamoswine" },
  { "id": 475, "name": "Gallade" },
  { "id": 478, "name": "Froslass" },
  { "id": 479, "name": "Rotom", "slug": "rotom" },
  { "id": 479, "name": "Rotom Calor", "slug": "rotom-heat" },
  { "id": 479, "name": "Rotom Lavado", "slug": "rotom-wash" },
  { "id": 479, "name": "Rotom Frío", "slug": "rotom-frost" },
  { "id": 479, "name": "Rotom Ventilador", "slug": "rotom-fan" },
  { "id": 479, "name": "Rotom Corte", "slug": "rotom-mow" },
  { "id": 497, "name": "Serperior" },
  { "id": 500, "name": "Emboar" },
  { "id": 503, "name": "Samurott" },
  { "id": 503, "name": "Samurott", "slug": "samurott-hisui" },
  { "id": 505, "name": "Watchog" },
  { "id": 505, "name": "Watchog" },
  { "id": 510, "name": "Liepard" },
  { "id": 512, "name": "Simisage" },
  { "id": 514, "name": "Simisear" },
  { "id": 516, "name": "Simipour" },
  { "id": 530, "name": "Excadrill" },
  { "id": 531, "name": "Audino" },
  { "id": 547, "name": "Whimsicott" },
  { "id": 553, "name": "Krookodile" },
  { "id": 563, "name": "Cofagrigus" },
  { "id": 569, "name": "Garbodor" },
  { "id": 571, "name": "Zoroark" },
  { "id": 571, "name": "Zoroark de Hisui","slug": "zoroark-hisui"},
  { "id": 579, "name": "Reuniclus" },
  { "id": 584, "name": "Vanilluxe" },
  { "id": 587, "name": "Emolga" },
  { "id": 609, "name": "Chandelure" },
  { "id": 614, "name": "Beartic" },
  { "id": 618, "name": "Stunfisk" },
  { "id": 618, "name": "Stunfisk", "slug":"stunfisk-galar" },
  { "id": 623, "name": "Golurk" },
  { "id": 635, "name": "Hydreigon" },
  { "id": 637, "name": "Volcarona" },
  { "id": 653, "name": "Chesnaught" },
  { "id": 655, "name": "Delphox" },
  { "id": 658, "name": "Greninja" },
  { "id": 660, "name": "Diggersby" },
  { "id": 663, "name": "Talonflame" },
  { "id": 666, "name": "Vivillon" },
  { "id": 670, "name": "Floette flor eterna","slug": "floette-eternal"},
  { "id": 671, "name": "Florges" },
  { "id": 675, "name": "Pangoro" },
  { "id": 675, "name": "Furfrou" },
  { "id": 678, "name": "Meowstic", "slug": "meowstic" },
  { "id": 681, "name": "Aegislash", "slug": "aegislash-shield"},
  { "id": 683, "name": "Aromatisse" },
  { "id": 685, "name": "Slurpuff" },
  { "id": 693, "name": "Clawitzer" },
  { "id": 695, "name": "Heliolisk" },
  { "id": 697, "name": "Tyrantrum" },
  { "id": 699, "name": "Aurorus" },
  { "id": 700, "name": "Sylveon" },
  { "id": 701, "name": "Hawlucha" },
  { "id": 702, "name": "Dedenne", "slug": "dedenne" },
  { "id": 706, "name": "Goodra" },
  { "id": 707, "name": "Klefki" },
  { "id": 709, "name": "Trevenant"},
  { "id": 706, "name": "Goodra de Hisui", "slug": "goodra-hisui" },
  { "id": 711, "name": "Gourgeist", "slug": "gourgeist-large" },
  { "id": 713, "name": "Avalugg", "slug": "avalugg" },
  { "id": 713, "name": "Avalugg de Hisui", "slug": "avalugg-hisui" },
  { "id": 715, "name": "Noivern" },
  { "id": 724, "name": "Decidueye" },
  { "id": 724, "name": "Decidueye de Hisui", "slug": "decidueye-hisui" },
  { "id": 727, "name": "Incineroar" },
  { "id": 730, "name": "Primarina" },
  { "id": 733, "name": "Toucannon"},
  { "id": 740, "name": "Crabominable" },
  { "id": 745, "name": "Lycanroc" },
  { "id": 748, "name": "Toxapex" },
  { "id": 750, "name": "Mudsdale" },
  { "id": 752, "name": "Araquanid" },
  { "id": 758, "name": "Salazzle" },
  { "id": 763, "name": "Tsareena" },
  { "id": 765, "name": "Oranguru" },
  { "id": 766, "name": "Passimian" },
  { "id": 778, "name": "Mimikyu" },
  { "id": 780, "name": "Drampa" },
  { "id": 784, "name": "Kommo-o" },
  { "id": 823, "name": "Corviknight" },
  { "id": 841, "name": "Flapple" },
  { "id": 842, "name": "Appletun" },
  { "id": 844, "name": "Sandaconda" },
  { "id": 855, "name": "Polteageist" },
  { "id": 858, "name": "Hatterene" },
  { "id": 866, "name": "Mr. Rime","slug": "mr-rime" },
  { "id": 867, "name": "Runerigus" },
  { "id": 869, "name": "Alcremie" },
  { "id": 877, "name": "Morpeko", "slug": "morpeko-hangry" },
  { "id": 887, "name": "Dragapult" },
  { "id": 899, "name": "Wyrdeer" },
  { "id": 900, "name": "Kleavor" },
  { "id": 902, "name": "Basculegion", "slug": "basculegion-male" },
  { "id": 902, "name": "Basculegion", "slug": "basculegion-female" },
  { "id": 903, "name": "Sneasler" },
  { "id": 908, "name": "Meowscarada" },
  { "id": 911, "name": "Skeledirge" },
  { "id": 914, "name": "Quaquaval" },
  { "id": 925, "name": "Maushold", "slug": "tandemaus" },
  { "id": 934, "name": "Garganacl" },
  { "id": 936, "name": "Armarouge" },
  { "id": 937, "name": "Ceruledge" },
  { "id": 939, "name": "Bellibolt" },
  { "id": 952, "name": "Scovillain" },
  { "id": 956, "name": "Espathra" },
  { "id": 959, "name": "Tinkaton" },
  { "id": 964, "name": "Palafin" },
  { "id": 968, "name": "Orthworm" },
  { "id": 970, "name": "Glimmora" },
  { "id": 981, "name": "Farigiraf" },
  { "id": 983, "name": "Kingambit" },
  { "id": 1013, "name": "Sinistcha" },
  { "id": 1018, "name": "Archaludon" },
  { "id": 1019, "name": "Hydrapple" },

  // Megaevoluciones
  { "id": 3, "name": "Mega-Venusaur", "slug": "venusaur-mega" },
  { "id": 6, "name": "Mega-Charizard X", "slug": "charizard-mega-x" },
  { "id": 6, "name": "Mega-Charizard Y", "slug": "charizard-mega-y" },
  { "id": 9, "name": "Mega-Blastoise", "slug": "blastoise-mega" },
  { "id": 15, "name": "Mega-Beedrill", "slug": "beedrill-mega" },
  { "id": 18, "name": "Mega-Pidgeot", "slug": "pidgeot-mega" },
  { "id": 36, "name": "Mega-Clefable", "slug": "clefable-mega" },
  { "id": 65, "name": "Mega-Alakazam", "slug": "alakazam-mega" },
  { "id": 71, "name": "Mega-Victreebel", "slug": "victreebel-mega" },
  { "id": 80, "name": "Mega-Slowbro", "slug": "slowbro-mega" },
  { "id": 94, "name": "Mega-Gengar", "slug": "gengar-mega" },
  { "id": 115, "name": "Mega-Kangaskhan", "slug": "kangaskhan-mega" },
  { "id": 121, "name": "Mega-Starmie", "slug": "starmie-mega" },
  { "id": 127, "name": "Mega-Pinsir", "slug": "pinsir-mega" },
  { "id": 130, "name": "Mega-Gyarados", "slug": "gyarados-mega" },
  { "id": 142, "name": "Mega-Aerodactyl", "slug": "aerodactyl-mega" },
  { "id": 149, "name": "Mega-Dragonite", "slug": "dragonite-mega" },
  { "id": 154, "name": "Mega-Meganium", "slug": "meganium-mega" },
  { "id": 160, "name": "Mega-Feraligatr", "slug": "feraligatr-mega" }
];

// Archivo importado por el usuario. La app puede usar `QUESTIONS` para generar quizzes

// Puedes usar esta variable en la app para forzar el banco Champions.
