// Script: prefetch_pokeapi.js
// Lee /questions.js del proyecto, consulta la PokeAPI por cada ID y genera
// /precache/poke_api_cache_v1.js que, al cargarse en el navegador, escribe la
// cache en localStorage bajo la clave 'poke_api_cache_v1'.

const fs = require('fs');
const path = require('path');

const QUESTIONS_PATH = path.resolve(__dirname, '..', 'questions.js');
const OUT_DIR = path.resolve(__dirname, '..', 'precache');
const OUT_FILE = path.join(OUT_DIR, 'poke_api_cache_v1.js');

function pickSprite(data){
  if(!data || !data.sprites) return null;
  return data.sprites.other?.home?.front_default
    || data.sprites.other?.['official-artwork']?.front_default
    || data.sprites.other?.dream_world?.front_default
    || data.sprites.front_default
    || null;
}

async function fetchJson(url){
  if (typeof fetch === 'undefined'){
    const https = require('https');
    return new Promise((res, rej)=>{
      https.get(url, (r)=>{
        let data=''; r.on('data', c=>data+=c); r.on('end', ()=>{ try{ res(JSON.parse(data)); }catch(e){ rej(e);} }); r.on('error', rej);
      });
    });
  }
  const r = await fetch(url); if(!r.ok) throw new Error('HTTP '+r.status); return await r.json();
}

async function main(){
  if(!fs.existsSync(QUESTIONS_PATH)) { console.error('No existe', QUESTIONS_PATH); process.exit(1); }
  const qtxt = fs.readFileSync(QUESTIONS_PATH,'utf8');
  // evaluate QUESTIONS by wrapping
  let QUESTIONS;
  try{
    // crude eval: extract const QUESTIONS = ...;
    const m = qtxt.match(/const\s+QUESTIONS\s*=\s*(\[([\s\S]*)\]);/m);
    if(!m) throw new Error('No se encontró QUESTIONS en questions.js');
    QUESTIONS = eval(m[1]);
  }catch(e){ console.error('Error parseando QUESTIONS:', e.message); process.exit(1); }

  const entries = {};
  for(const q of QUESTIONS){
    const id = q.id;
    if(!id) continue;
    const key = `id-${id}`;
    if(entries[key]) continue;
    try{
      console.log('Fetching', id, q.name);
      const data = await fetchJson(`https://pokeapi.co/api/v2/pokemon/${id}`);
      const types = (data.types||[]).map(t=>t.type.name.charAt(0).toUpperCase()+t.type.name.slice(1)).join('/');
      const sprite = pickSprite(data);
      entries[key] = { name: data.name, types, sprite };
    }catch(e){
      console.warn('No encontrado en PokeAPI:', id, q.name, e.message);
      entries[key] = { name: q.name, types: 'Unknown', sprite: null };
    }
  }

  if(!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR);
  const outJs = `// Autogenerated prefetch cache for PokeAPI\n(function(){try{localStorage.setItem('poke_api_cache_v1', JSON.stringify(${JSON.stringify(entries, null, 2)})); console.log('poke_api_cache_v1 loaded with ${Object.keys(entries).length} entries');}catch(e){console.warn('prefetch load failed', e);} })();\n`;
  fs.writeFileSync(OUT_FILE, outJs, 'utf8');
  console.log('Wrote', OUT_FILE);
}

main().catch(e=>{ console.error(e); process.exit(1); });
