// Autogenerated prefetch cache for PokeAPI
(function(){try{localStorage.setItem('poke_api_cache_v1', JSON.stringify({
  "id-3": {
    "name": "venusaur",
    "types": "Grass/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png"
  },
  "id-6": {
    "name": "charizard",
    "types": "Fire/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png"
  },
  "id-9": {
    "name": "blastoise",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png"
  },
  "id-15": {
    "name": "beedrill",
    "types": "Bug/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png"
  },
  "id-18": {
    "name": "pidgeot",
    "types": "Normal/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png"
  },
  "id-24": {
    "name": "arbok",
    "types": "Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/24.png"
  },
  "id-25": {
    "name": "pikachu",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png"
  },
  "id-26": {
    "name": "raichu",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png"
  },
  "id-36": {
    "name": "clefable",
    "types": "Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/36.png"
  },
  "id-38": {
    "name": "ninetales",
    "types": "Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/38.png"
  },
  "id-59": {
    "name": "arcanine",
    "types": "Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/59.png"
  },
  "id-65": {
    "name": "alakazam",
    "types": "Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/65.png"
  },
  "id-68": {
    "name": "machamp",
    "types": "Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/68.png"
  },
  "id-71": {
    "name": "victreebel",
    "types": "Grass/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/71.png"
  },
  "id-80": {
    "name": "slowbro",
    "types": "Water/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/80.png"
  },
  "id-94": {
    "name": "gengar",
    "types": "Ghost/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/94.png"
  },
  "id-115": {
    "name": "kangaskhan",
    "types": "Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/115.png"
  },
  "id-121": {
    "name": "starmie",
    "types": "Water/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/121.png"
  },
  "id-127": {
    "name": "pinsir",
    "types": "Bug",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/127.png"
  },
  "id-128": {
    "name": "tauros",
    "types": "Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/128.png"
  },
  "id-130": {
    "name": "gyarados",
    "types": "Water/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/130.png"
  },
  "id-132": {
    "name": "ditto",
    "types": "Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/132.png"
  },
  "id-134": {
    "name": "vaporeon",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/134.png"
  },
  "id-135": {
    "name": "jolteon",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/135.png"
  },
  "id-136": {
    "name": "flareon",
    "types": "Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/136.png"
  },
  "id-142": {
    "name": "aerodactyl",
    "types": "Rock/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/142.png"
  },
  "id-143": {
    "name": "snorlax",
    "types": "Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/143.png"
  },
  "id-149": {
    "name": "dragonite",
    "types": "Dragon/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/149.png"
  },
  "id-154": {
    "name": "meganium",
    "types": "Grass",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/154.png"
  },
  "id-157": {
    "name": "typhlosion",
    "types": "Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/157.png"
  },
  "id-160": {
    "name": "feraligatr",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/160.png"
  },
  "id-181": {
    "name": "ampharos",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/181.png"
  },
  "id-184": {
    "name": "azumarill",
    "types": "Water/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/184.png"
  },
  "id-186": {
    "name": "politoed",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/186.png"
  },
  "id-196": {
    "name": "espeon",
    "types": "Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/196.png"
  },
  "id-197": {
    "name": "umbreon",
    "types": "Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/197.png"
  },
  "id-199": {
    "name": "slowking",
    "types": "Water/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/199.png"
  },
  "id-212": {
    "name": "scizor",
    "types": "Bug/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/212.png"
  },
  "id-214": {
    "name": "heracross",
    "types": "Bug/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/214.png"
  },
  "id-229": {
    "name": "houndoom",
    "types": "Dark/Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/229.png"
  },
  "id-248": {
    "name": "tyranitar",
    "types": "Rock/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/248.png"
  },
  "id-257": {
    "name": "blaziken",
    "types": "Fire/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/257.png"
  },
  "id-260": {
    "name": "swampert",
    "types": "Water/Ground",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/260.png"
  },
  "id-282": {
    "name": "gardevoir",
    "types": "Psychic/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/282.png"
  },
  "id-303": {
    "name": "mawile",
    "types": "Steel/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/303.png"
  },
  "id-306": {
    "name": "aggron",
    "types": "Steel/Rock",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/306.png"
  },
  "id-308": {
    "name": "medicham",
    "types": "Fighting/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/308.png"
  },
  "id-310": {
    "name": "manectric",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/310.png"
  },
  "id-330": {
    "name": "flygon",
    "types": "Ground/Dragon",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/330.png"
  },
  "id-334": {
    "name": "altaria",
    "types": "Dragon/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/334.png"
  },
  "id-354": {
    "name": "banette",
    "types": "Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/354.png"
  },
  "id-359": {
    "name": "absol",
    "types": "Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/359.png"
  },
  "id-362": {
    "name": "glalie",
    "types": "Ice",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/362.png"
  },
  "id-373": {
    "name": "salamence",
    "types": "Dragon/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/373.png"
  },
  "id-376": {
    "name": "metagross",
    "types": "Steel/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/376.png"
  },
  "id-380": {
    "name": "latias",
    "types": "Dragon/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/380.png"
  },
  "id-381": {
    "name": "latios",
    "types": "Dragon/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/381.png"
  },
  "id-384": {
    "name": "rayquaza",
    "types": "Dragon/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/384.png"
  },
  "id-392": {
    "name": "infernape",
    "types": "Fire/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/392.png"
  },
  "id-405": {
    "name": "luxray",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/405.png"
  },
  "id-407": {
    "name": "roserade",
    "types": "Grass/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/407.png"
  },
  "id-423": {
    "name": "gastrodon",
    "types": "Water/Ground",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/423.png"
  },
  "id-445": {
    "name": "garchomp",
    "types": "Dragon/Ground",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/445.png"
  },
  "id-448": {
    "name": "lucario",
    "types": "Fighting/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/448.png"
  },
  "id-460": {
    "name": "abomasnow",
    "types": "Grass/Ice",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/460.png"
  },
  "id-461": {
    "name": "weavile",
    "types": "Dark/Ice",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/461.png"
  },
  "id-468": {
    "name": "togekiss",
    "types": "Fairy/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/468.png"
  },
  "id-475": {
    "name": "gallade",
    "types": "Psychic/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/475.png"
  },
  "id-479": {
    "name": "rotom",
    "types": "Electric/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/479.png"
  },
  "id-488": {
    "name": "cresselia",
    "types": "Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/488.png"
  },
  "id-530": {
    "name": "excadrill",
    "types": "Ground/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/530.png"
  },
  "id-547": {
    "name": "whimsicott",
    "types": "Grass/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/547.png"
  },
  "id-553": {
    "name": "krookodile",
    "types": "Ground/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/553.png"
  },
  "id-569": {
    "name": "garbodor",
    "types": "Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/569.png"
  },
  "id-571": {
    "name": "zoroark",
    "types": "Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/571.png"
  },
  "id-579": {
    "name": "reuniclus",
    "types": "Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/579.png"
  },
  "id-594": {
    "name": "alomomola",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/594.png"
  },
  "id-609": {
    "name": "chandelure",
    "types": "Ghost/Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/609.png"
  },
  "id-612": {
    "name": "haxorus",
    "types": "Dragon",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/612.png"
  },
  "id-635": {
    "name": "hydreigon",
    "types": "Dark/Dragon",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/635.png"
  },
  "id-637": {
    "name": "volcarona",
    "types": "Bug/Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/637.png"
  },
  "id-645": {
    "name": "landorus-incarnate",
    "types": "Ground/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/645.png"
  },
  "id-658": {
    "name": "greninja",
    "types": "Water/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/658.png"
  },
  "id-663": {
    "name": "talonflame",
    "types": "Fire/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/663.png"
  },
  "id-678": {
    "name": "meowstic-male",
    "types": "Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/678.png"
  },
  "id-683": {
    "name": "aromatisse",
    "types": "Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/683.png"
  },
  "id-700": {
    "name": "sylveon",
    "types": "Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/700.png"
  },
  "id-701": {
    "name": "hawlucha",
    "types": "Fighting/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/701.png"
  },
  "id-706": {
    "name": "goodra",
    "types": "Dragon",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/706.png"
  },
  "id-715": {
    "name": "noivern",
    "types": "Flying/Dragon",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/715.png"
  },
  "id-717": {
    "name": "yveltal",
    "types": "Dark/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/717.png"
  },
  "id-724": {
    "name": "decidueye",
    "types": "Grass/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/724.png"
  },
  "id-727": {
    "name": "incineroar",
    "types": "Fire/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/727.png"
  },
  "id-730": {
    "name": "primarina",
    "types": "Water/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/730.png"
  },
  "id-745": {
    "name": "lycanroc-midday",
    "types": "Rock",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/745.png"
  },
  "id-748": {
    "name": "toxapex",
    "types": "Poison/Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/748.png"
  },
  "id-778": {
    "name": "mimikyu-disguised",
    "types": "Ghost/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/778.png"
  },
  "id-784": {
    "name": "kommo-o",
    "types": "Dragon/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/784.png"
  },
  "id-797": {
    "name": "celesteela",
    "types": "Steel/Flying",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/797.png"
  },
  "id-806": {
    "name": "blacephalon",
    "types": "Fire/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/806.png"
  },
  "id-812": {
    "name": "rillaboom",
    "types": "Grass",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/812.png"
  },
  "id-815": {
    "name": "cinderace",
    "types": "Fire",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/815.png"
  },
  "id-818": {
    "name": "inteleon",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/818.png"
  },
  "id-823": {
    "name": "corviknight",
    "types": "Flying/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/823.png"
  },
  "id-826": {
    "name": "orbeetle",
    "types": "Bug/Psychic",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/826.png"
  },
  "id-858": {
    "name": "hatterene",
    "types": "Psychic/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/858.png"
  },
  "id-861": {
    "name": "grimmsnarl",
    "types": "Dark/Fairy",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/861.png"
  },
  "id-887": {
    "name": "dragapult",
    "types": "Dragon/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/887.png"
  },
  "id-892": {
    "name": "urshifu-single-strike",
    "types": "Fighting/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/892.png"
  },
  "id-897": {
    "name": "spectrier",
    "types": "Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/897.png"
  },
  "id-901": {
    "name": "ursaluna",
    "types": "Ground/Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/901.png"
  },
  "id-903": {
    "name": "sneasler",
    "types": "Fighting/Poison",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/903.png"
  },
  "id-908": {
    "name": "meowscarada",
    "types": "Grass/Dark",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/908.png"
  },
  "id-911": {
    "name": "skeledirge",
    "types": "Fire/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/911.png"
  },
  "id-914": {
    "name": "quaquaval",
    "types": "Water/Fighting",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/914.png"
  },
  "id-930": {
    "name": "arboliva",
    "types": "Grass/Normal",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/930.png"
  },
  "id-937": {
    "name": "ceruledge",
    "types": "Fire/Ghost",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/937.png"
  },
  "id-938": {
    "name": "tadbulb",
    "types": "Electric",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/938.png"
  },
  "id-959": {
    "name": "tinkaton",
    "types": "Fairy/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/959.png"
  },
  "id-964": {
    "name": "palafin-zero",
    "types": "Water",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/964.png"
  },
  "id-983": {
    "name": "kingambit",
    "types": "Dark/Steel",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/983.png"
  }
})); console.log('poke_api_cache_v1 loaded with 121 entries');}catch(e){console.warn('prefetch load failed', e);} })();
